# INITIAL SETTINGS
train_file: train_split_1_4.csv
val_file: val_split_1_4.csv

# TRAINING SETTINGS
batch_size: 10
num_workers: 0
epochs: 1
lr: 0.003000
weight_decay: 0.000010

# VALIDATION SETTINGS
threshold: 0.500000

# DEVICE CONFIGS
device_count: 1
